// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/liukaixin/local/ns-widget/node_modules/.pnpm/dumi@2.4.10_@babel+core@7.25.2_@swc+helpers@0.5.1_@types+node@22.5.5_@types+react@18.3.5_esli_qbhgcffbzhqecyoejdbwxs4yjy/node_modules/dumi/theme-default/builtins/Tree/index.js';
