// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/Button":{"path":"button","id":"docs/Button","parentId":"DocLayout"},"docs/Modal":{"path":"modal","id":"docs/Modal","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/liukaixin/local/ns-widget/node_modules/.pnpm/dumi@2.4.10_@babel+core@7.25.2_@swc+helpers@0.5.1_@types+node@22.5.5_@types+react@18.3.5_esli_qbhgcffbzhqecyoejdbwxs4yjy/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/liukaixin/local/ns-widget/packages/styled/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/liukaixin/local/ns-widget/node_modules/.pnpm/dumi@2.4.10_@babel+core@7.25.2_@swc+helpers@0.5.1_@types+node@22.5.5_@types+react@18.3.5_esli_qbhgcffbzhqecyoejdbwxs4yjy/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/Button': React.lazy(() => import(/* webpackChunkName: "docs__Button.md" */'/Users/liukaixin/local/ns-widget/packages/styled/docs/Button.md')),
'docs/Modal': React.lazy(() => import(/* webpackChunkName: "docs__Modal.md" */'/Users/liukaixin/local/ns-widget/packages/styled/docs/Modal.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/liukaixin/local/ns-widget/packages/styled/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/liukaixin/local/ns-widget/node_modules/.pnpm/dumi@2.4.10_@babel+core@7.25.2_@swc+helpers@0.5.1_@types+node@22.5.5_@types+react@18.3.5_esli_qbhgcffbzhqecyoejdbwxs4yjy/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
